### PR TITLE
Added logout button.

### PR DESCRIPTION
**Pull request by msaivasanth**
Added LogOut button

### CODE REVIEW

**Review by syedzeeshan1 — COMMENTED** [review]
Can we add a functionality to keep a session timeout? the token expires after certain period of time of being idle on the page.

Just to make things a bit complex.. this MR is very easy and straightforward.

**Comment by msaivasanth** [comment]
> Can we add a functionality to keep a session timeout? the token expires after certain period of time of being idle on the page.
> 
> Just to make things a bit complex.. this MR is very easy and straightforward.

So should I remove the check for token is expired or not, and keep a new session timeout functionality.

**Comment by syedzeeshan1** [comment]
You can try having both.. idle expiration or regular timeout.

**Comment by msaivasanth** [comment]
How much time should we give for session timeout. I mean after how much time the session should be timed out.

**Review by syedzeeshan1 — APPROVED** [review]
Perfect!

**Pull request merged**
