### PR TITLE
Replaced dummy api with localhost

### PR DESCRIPTION
**Pull request by msaivasanth**
Created a localhost api for login, used it instead of dummy api.

### CODE REVIEW

**Review by syedzeeshan1 — COMMENTED** [review]
did you test your login API? 
Does your login API have a timeout and gives back a cookie to store?

**Comment by msaivasanth** [comment]
Yes, I tested my api in postman, and it will return a token whenever we call the api. The token will expire for every 5 mins. 

But I also need to write an api for checking the status of token, i.e., whether the token is expired or not, as I am using dummy api for checking the token status.

**Comment by syedzeeshan1** [comment]
> Yes, I tested my api in postman, and it will return a token whenever we call the api. The token will expire for every 5 mins.
> 
> But I also need to write an api for checking the status of token, i.e., whether the token is expired or not, as I am using dummy api for checking the token status.

Do you want to cover that part in this MR?

**Comment by msaivasanth** [comment]
> > Yes, I tested my api in postman, and it will return a token whenever we call the api. The token will expire for every 5 mins.
> > But I also need to write an api for checking the status of token, i.e., whether the token is expired or not, as I am using dummy api for checking the token status.
> 
> Do you want to cover that part in this MR?

Yes sir.

**Comment by msaivasanth** [comment]
> > Yes, I tested my api in postman, and it will return a token whenever we call the api. The token will expire for every 5 mins.
> > But I also need to write an api for checking the status of token, i.e., whether the token is expired or not, as I am using dummy api for checking the token status.
> 
> Do you want to cover that part in this MR?

Yes sir, I want to cover this part in this MR.

**Review by syedzeeshan1 — APPROVED** [review]
Awesome work! :shipit:

**Pull request merged**
